"""Adiciona flag 'is_remetente' ao Cliente

Revision ID: 3a9d189ac2aa
Revises: e9ca09a0b246
Create Date: 2025-10-28 13:40:25.316190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a9d189ac2aa'
down_revision = 'e9ca09a0b246'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_remetente', sa.Boolean(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.drop_column('is_remetente')

    # ### end Alembic commands ###
