"""Sincroniza banco online com V7

Revision ID: 5cfd8990b43b
Revises: 
Create Date: 2025-11-04 13:20:32.895226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cfd8990b43b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cargas', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_cargas_veiculo_id_veiculos'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_cargas_motorista_id_motoristas'), type_='foreignkey')

    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_remetente', sa.Boolean(), nullable=False, server_default='false'))

    with op.batch_alter_table('entregas', schema=None) as batch_op:
        batch_op.alter_column('remetente_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('4491'))
        batch_op.drop_constraint(batch_op.f('fk_entregas_remetente_id_clientes'), type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entregas', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_entregas_remetente_id_clientes'), 'clientes', ['remetente_id'], ['id'], initially='DEFERRED', deferrable=True)
        batch_op.alter_column('remetente_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('4491'))

    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.drop_column('is_remetente')

    with op.batch_alter_table('cargas', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_cargas_motorista_id_motoristas'), 'motoristas', ['motorista_id'], ['id'], initially='DEFERRED', deferrable=True)
        batch_op.create_foreign_key(batch_op.f('fk_cargas_veiculo_id_veiculos'), 'veiculos', ['veiculo_id'], ['id'], initially='DEFERRED', deferrable=True)

    # ### end Alembic commands ###
