"""V2 - Adiciona Motorista, Veiculo e estrutura de Montagem

Revision ID: cadea4c7b5cd
Revises: 
Create Date: 2025-10-27 12:53:35.146643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cadea4c7b5cd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # Mantivemos comentados, pois já foram criados na primeira tentativa
    # op.create_table('motoristas',
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('codigo', sa.String(), nullable=True),
    # sa.Column('nome', sa.String(), nullable=False),
    # sa.PrimaryKeyConstraint('id'),
    # sa.UniqueConstraint('codigo')
    # )
    # op.create_table('veiculos',
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('placa', sa.String(), nullable=False),
    # sa.PrimaryKeyConstraint('id'),
    # sa.UniqueConstraint('placa')
    # )

    with op.batch_alter_table('cargas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('motorista_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('veiculo_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('frete_pago', sa.Float(), nullable=True))
        # O Alembic pode gerar nomes diferentes, mas tentaremos criar com nomes padrão para o downgrade saber
        batch_op.create_foreign_key('cargas_veiculo_id_fkey', 'veiculos', ['veiculo_id'], ['id']) # Nome adicionado
        batch_op.create_foreign_key('cargas_motorista_id_fkey', 'motoristas', ['motorista_id'], ['id']) # Nome adicionado
        batch_op.drop_column('motorista')
        batch_op.drop_column('placa')

    with op.batch_alter_table('entregas', schema=None) as batch_op:
        # A coluna 'peso_cobrado' existe no seu banco V1, não vamos apagá-la aqui.
        # batch_op.drop_column('peso_cobrado') # Mantido comentado
        batch_op.add_column(sa.Column('remetente_id', sa.Integer(), nullable=False, server_default='4491')) # ID do seu remetente padrão
        batch_op.add_column(sa.Column('peso_cubado', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('nota_fiscal', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('cidade_entrega', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('estado_entrega', sa.String(), nullable=True))
        batch_op.alter_column('carga_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        # O Alembic pode gerar nomes diferentes, mas tentaremos criar com nomes padrão para o downgrade saber
        batch_op.create_foreign_key('entregas_remetente_id_fkey', 'clientes', ['remetente_id'], ['id']) # Nome adicionado

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entregas', schema=None) as batch_op:
        # A coluna peso_cobrado não foi removida no upgrade, então não precisa ser adicionada aqui
        # batch_op.add_column(sa.Column('peso_cobrado', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))

        # === CORREÇÃO APLICADA AQUI ===
        # Substituímos None pelo nome padrão da constraint
        batch_op.drop_constraint('entregas_remetente_id_fkey', type_='foreignkey')
        # === FIM DA CORREÇÃO ===

        batch_op.alter_column('carga_id',
               existing_type=sa.INTEGER(),
               nullable=False) # Voltando para NOT NULL
        batch_op.drop_column('estado_entrega')
        batch_op.drop_column('cidade_entrega')
        batch_op.drop_column('nota_fiscal')
        batch_op.drop_column('peso_cubado')
        batch_op.drop_column('remetente_id')


    with op.batch_alter_table('cargas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('placa', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('motorista', sa.VARCHAR(), autoincrement=False, nullable=True))

        # === CORREÇÃO APLICADA AQUI ===
        # Substituímos None pelos nomes padrão das constraints
        batch_op.drop_constraint('cargas_veiculo_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('cargas_motorista_id_fkey', type_='foreignkey')
        # === FIM DA CORREÇÃO ===

        batch_op.drop_column('frete_pago')
        batch_op.drop_column('veiculo_id')
        batch_op.drop_column('motorista_id')

    # Mantivemos comentados
    # op.drop_table('veiculos')
    # op.drop_table('motoristas')
    # ### end Alembic commands ###