"""V2 - Recriacao local limpa sem .env

Revision ID: e9ca09a0b246
Revises: 
Create Date: 2025-10-28 12:33:47.633462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9ca09a0b246'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo_cliente', sa.String(), nullable=False),
    sa.Column('razao_social', sa.String(), nullable=False),
    sa.Column('ddd', sa.String(), nullable=True),
    sa.Column('telefone', sa.String(), nullable=True),
    sa.Column('cidade', sa.String(), nullable=True),
    sa.Column('estado', sa.String(), nullable=True),
    sa.Column('observacoes', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo_cliente')
    )
    op.create_table('motoristas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(), nullable=True),
    sa.Column('nome', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_usuario', sa.String(), nullable=False),
    sa.Column('senha_hash', sa.String(), nullable=False),
    sa.Column('permissao', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome_usuario')
    )
    op.create_table('veiculos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('placa', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('placa')
    )
    op.create_table('cargas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo_carga', sa.String(), nullable=False),
    sa.Column('origem', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('motorista_id', sa.Integer(), nullable=True),
    sa.Column('veiculo_id', sa.Integer(), nullable=True),
    sa.Column('frete_pago', sa.Float(), nullable=True),
    sa.Column('data_agendamento', sa.String(), nullable=True),
    sa.Column('data_carregamento', sa.String(), nullable=True),
    sa.Column('previsao_entrega', sa.String(), nullable=True),
    sa.Column('observacoes', sa.String(), nullable=True),
    sa.Column('data_finalizacao', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['motorista_id'], ['motoristas.id'], ),
    sa.ForeignKeyConstraint(['veiculo_id'], ['veiculos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo_carga')
    )
    op.create_table('entregas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('carga_id', sa.Integer(), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('remetente_id', sa.Integer(), nullable=False),
    sa.Column('peso_bruto', sa.Float(), nullable=True),
    sa.Column('valor_frete', sa.Float(), nullable=True),
    sa.Column('peso_cubado', sa.Float(), nullable=True),
    sa.Column('nota_fiscal', sa.String(), nullable=True),
    sa.Column('cidade_entrega', sa.String(), nullable=True),
    sa.Column('estado_entrega', sa.String(), nullable=True),
    sa.Column('is_last_delivery', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['carga_id'], ['cargas.id'], ),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['remetente_id'], ['clientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('entregas')
    op.drop_table('cargas')
    op.drop_table('veiculos')
    op.drop_table('usuarios')
    op.drop_table('motoristas')
    op.drop_table('clientes')
    # ### end Alembic commands ###
